name: starport

on: workflow_dispatch

jobs:
  starport:
    runs-on: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.5.0
        with:
          version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build
        run: |
          cd starport
          bash build.sh

      - name: Compress
        run: xz -T $(nproc) starport/images/starport.img
    

      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: sos
          path: starport/images/starport.img.xz
